// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';

import 'package:git_mobile/bridge_generated/api.dart' as api_gen;
import 'package:git_mobile/bridge_generated/git.dart' as git_gen;
import 'package:git_mobile/bridge_generated/ssh.dart' as ssh_gen;
// Re-export the bridge so it is only necessary to import this file.
import 'dart:io' as io;

const _base = 'libgit2_bindings';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylib = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';

// The late modifier delays initializing the value until it is actually needed,
// leaving precious little time for the program to quickly start up.
late final api_gen.ApiPlatform api = api_gen.ApiPlatformImpl(
    io.Platform.isIOS ? DynamicLibrary.process() : DynamicLibrary.open(_dylib));

late final git_gen.ApiGit git = git_gen.ApiGitImpl(
    io.Platform.isIOS ? DynamicLibrary.process() : DynamicLibrary.open(_dylib));

late final ssh_gen.ApiSsh ssh = ssh_gen.ApiSshImpl(
    io.Platform.isIOS ? DynamicLibrary.process() : DynamicLibrary.open(_dylib));
