name: publish
on:
  push

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Auto Publish
        run: |
          git remote add public https://github-actions:${AUTO_PUSH_TOKEN}@github.com/team-vinu/git_mobile_public
          git fetch -a
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GIHUB_ACTOR}@users.noreply.github.com"
          git checkout public
          git push public public
