name: publish
on:
  push

jobs:
  build:
    name: publish
    env:
      AUTO_PUSH_TOKEN: ${{secrets.AUTO_PUSH_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Auto Publish
        run: |
          git remote set-url origin https://anosatsuk124:${AUTO_PUSH_TOKEN}@github.com/team-vinu/git_mobile_public.git
          git fetch -a
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GIHUB_ACTOR}@users.noreply.github.com"
          git checkout public
          git push origin public
